# Generated by Django 5.1.3 on 2024-12-02 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_board_permitted_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
